MVC_PROG3/PhoneShop.Web/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhoneShop.Web.Models
{
	public class Customer
	{
		[Display(Name = "Customer Id")]
		[Required]
		public int Id { get; set; }

		[Display(Name = "Work Id")]
		[Required]
		public int WorkId { get; set; }

		[Display(Name = "Customer name")]
		[Required]
		public string Name { get; set; }

		[Display(Name = "Customer email")]
		[Required]
		public string Email { get; set; }

		[Display(Name = "Customer phone number")]
		[Required]
		public string PhoneNumber { get; set; }

		[Display(Name = "Customer date")]
		[Required]
		public string Date { get; set; }

		[Display(Name = "Customer points")]
		[Required]
		public int CustomerPoints { get; set; }
	}
}

MVC_PROG3/PhoneShop.Web/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhoneShop.Web.Models
{
	public class CustomerViewModel
	{
		public Customer EditCustomer { get; set; }
		public List<Customer> ListOfCustomres { get; set; }
	}
}

MVC_PROG3/PhoneShop.Web/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PhoneShop.Data;
using PhoneShop.Logic;
using PhoneShop.Repository;
using PhoneShop.Web.Models;

namespace PhoneShop.Web.Controllers
{
    public class CustomerController : Controller
    {
        ICustomerLogic logic;
        IMapper mapper;
        CustomerViewModel vm;
        public CustomerController()
        {
            PhoneShopDataBaseEntities db = new PhoneShopDataBaseEntities();
            CustomerRepository customRepo = new CustomerRepository(db);
            logic = new CustomerLogic(customRepo);
            mapper = MapperFactory.CreateMapper();
            vm = new CustomerViewModel();
            vm.EditCustomer = new Customer();
            var customers = logic.Getall().ToList();
            vm.ListOfCustomres = mapper.Map<IList<Data.CUSTOMER>, List<Models.Customer>>(customers);

        }
        private Customer GetCustomerModel(int id)
        {
            CUSTOMER oneCustomer = logic.GetOne(id);
            return mapper.Map<Data.CUSTOMER, Models.Customer>(oneCustomer);
        }
        // GET: Customer
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("CustomerIndex", vm);
        }

        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View("CustomerDetails", GetCustomerModel(id));
        }

        // GET: Customer/Remove/5
        public ActionResult Remove(int id)
        {
            //TempData["editResult"] = "Delete FAIL";
            //if (logic.DeleteItem(id))
            //{

            //}
            logic.DeleteItem(id);
            TempData["editResult"] = "Delete OK";
            return RedirectToAction("Index");
        }
        //GET: Customer/edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditCustomer = GetCustomerModel(id);
            return View("CustomerIndex", vm);
        }
        // POST: Customer/Edit
        [HttpPost]
        public ActionResult Edit(Customer customer, string editAction)
        {
            CUSTOMER c = new CUSTOMER();
            c.customer_id = customer.Id;
            c.customer_name = customer.Name;
            c.customer_date = customer.Date;
            c.customer_email = customer.Email;
            c.customer_phonenumber = customer.PhoneNumber;
            c.customer_points = customer.CustomerPoints;
            c.customer_work = customer.WorkId;
            if (ModelState.IsValid && customer != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    logic.CreateItem(c);
                }
                else
                {
                    logic.EditCustomer(customer.Id, customer.Name, customer.Email, customer.PhoneNumber, customer.WorkId, customer.CustomerPoints, customer.Date);
                    //logic.UpdateEmail(customer.Id, "UpdatedEmail");
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditCustomer = customer;
                return View("CustomerIndex", vm);
            }
        }


        //// GET: Customer/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Customer/Create
        //[HttpPost]
        //public ActionResult Create(FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Customer/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Customer/Edit/5
        //[HttpPost]
        //public ActionResult Edit(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Customer/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Customer/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

MVC_PROG3/PhoneShop.Web/Views/Customer/CustomerDetails.cshtml
@model PhoneShop.Web.Models.Customer
@{
    ViewBag.Title = "CustomerDetails";
}

<h2>CustomerDetails</h2>
@Html.ActionLink("Go back to the list", "Index");
<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.WorkId)</td>
        <td>@Html.DisplayFor(m => m.WorkId)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Email)</td>
        <td>@Html.DisplayFor(m => m.Email)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.PhoneNumber)</td>
        <td>@Html.DisplayFor(m => m.PhoneNumber)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Date)</td>
        <td>@Html.DisplayFor(m => m.Date)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.CustomerPoints)</td>
        <td>@Html.DisplayFor(m => m.CustomerPoints)</td>
    </tr>
</table>

MVC_PROG3/PhoneShop.Web/Views/Customer/CustomerEdit.cshtml
@model PhoneShop.Web.Models.Customer

<h2>Edit one Customer</h2>

@using (Html.BeginForm("Edit", "Customer"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString())
    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Date)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Date)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Email)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Email)</div>

    <div class="editor-label">@Html.LabelFor(m => m.PhoneNumber)</div>
    <div class="editor-field">@Html.EditorFor(m => m.PhoneNumber)</div>

    <div class="editor-label">@Html.LabelFor(m => m.CustomerPoints)</div>
    <div class="editor-field">@Html.EditorFor(m => m.CustomerPoints)</div>

    <div class="editor-label">@Html.LabelFor(m => m.WorkId)</div>
    <div class="editor-field">@Html.EditorFor(m => m.WorkId)</div>

    <input type="submit" value="SEND"/>
}

MVC_PROG3/PhoneShop.Web/Views/Customer/CustomerIndex.cshtml
@model PhoneShop.Web.Models.CustomerViewModel
@{
    ViewBag.Title = "CustomerIndex";
}

<h2>CustomerIndex</h2>
<p style="color:red; font-weight: bold">@TempData["editResult"]</p>

@Html.Partial("CustomerEdit", Model.EditCustomer)
@Html.Partial("CustomerList", Model.ListOfCustomres)

MVC_PROG3/PhoneShop.Web/Views/Customer/CustomerList.cshtml
@model IEnumerable<PhoneShop.Web.Models.Customer>

<h2>List of customers</h2>
@if (Model.Count() == 0)
{
    <p>No data in the database</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>@Html.DisplayNameFor(m => m.First().Date)</th>
            <th>More details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.DisplayFor(m => item.Date)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id})</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}